DROP TABLE IF EXISTS prices;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS brands;
DROP TABLE IF EXISTS currencies;

CREATE TABLE brands (
                        id BIGINT PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL
);

CREATE TABLE products (
                          id BIGINT PRIMARY KEY,
                          name VARCHAR(150) NOT NULL,
                          active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL
);

CREATE TABLE currencies (
                            iso_code VARCHAR(3) PRIMARY KEY,
                            description VARCHAR(50) NOT NULL,
                            active BOOLEAN NOT NULL DEFAULT TRUE,
                            created_at TIMESTAMP NOT NULL,
                            updated_at TIMESTAMP NOT NULL
);

CREATE TABLE prices (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        brand_id BIGINT NOT NULL,
                        product_id BIGINT NOT NULL,
                        price_list INTEGER NOT NULL,
                        priority INTEGER NOT NULL,
                        start_date TIMESTAMP NOT NULL,
                        end_date TIMESTAMP NOT NULL,
                        price DECIMAL(10,2) NOT NULL,
                        currency_code VARCHAR(3) NOT NULL,
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL,

                        CONSTRAINT fk_prices_brand
                            FOREIGN KEY (brand_id) REFERENCES brands(id),

                        CONSTRAINT fk_prices_product
                            FOREIGN KEY (product_id) REFERENCES products(id),

                        CONSTRAINT fk_prices_currency
                            FOREIGN KEY (currency_code) REFERENCES currencies(iso_code)
);

CREATE INDEX idx_prices_search
    ON prices (brand_id, product_id, active, start_date, end_date, priority);